name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose -y

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-image:${{ github.sha }} .

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/my-image:${{ github.sha }}

    - name: Stop previous Docker Compose
      run: docker-compose down || true

    - name: Set environment variables
      run: |
        echo "DOCKER_IMAGE=${{ secrets.DOCKER_USERNAME }}/my-image:${{ github.sha }}" >> $GITHUB_ENV

    - name: Start Docker Compose
      run: docker-compose up -d

    - name: Wait for API to be available
      run: sleep 10

    - name: Install ngrok
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip

    - name: Run ngrok
      run: |
        ./ngrok http 8000 &

    - name: Get ngrok URL
      id: ngrok
      run: |
        sleep 5
        NGROK_URL=$(curl -s localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
        echo "::set-output name=url::$NGROK_URL"

    - name: Test API
      run: |
        echo "Ngrok URL: ${{ steps.ngrok.outputs.url }}"
        curl -X POST -H "Content-Type: application/json" -d '[{"tree_id": 536325, "block_id": 415591, "tree_dbh": 56, "curb_loc": 0, "spc_latin": "Fraxinus", "steward": "None", "guards": "Unsure", "sidewalk": 0, "user_type": "NYC Parks Staff", "problems": "NoProblem", "root_stone": 0, "root_grate": 0, "root_other": 0, "trunk_wire": 0, "trnk_light": 0, "trnk_other": 0, "brch_light": 0, "brch_shoe": 0, "brch_other": 0, "postcode": 10306, "borough": "Staten Island", "cncldist": 50, "st_assem": 62, "st_senate": 24, "nta": "SI24", "boro_ct": 5027900, "latitude": 40.571808, "longitude": -74.144251}]' ${{ steps.ngrok.outputs.url }}/predict_health/